repo: 'grid-ception'
canvasCourse: 'web-dev-3'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    outline: true
    has:
      - ['link[href*="grid.css"] + link[href*="main.css"]', 'The `grid.css` file must come before the `main.css` file.']
      - 'h1'
      - 'h2'
      - 'p'
      - 'dl'
      - 'dl > dt'
      - 'dl > dd'
      - 'img[class~="img-flex"]'
      - 'div[class~="grid"]'
      - 'div[class~="unit"]'
      - 'div[class*="xs-"]'
      - 'div[class*="s-"]'
      - 'div[class*="m-"]'
      - 'div[class*="l-"]'
      - 'time[datetime]'
    has_not:
      - 'br'
    search:
      - 'Moons of Mars'
      - 'Deimos'
      - 'Phobos'
      - 'Deimosian'
      - 'Phobian'
      - 'Asaph Hall'
      - 'August 17, 1877'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['html', 'text-size-adjust', '100%']
      - ['html', '-moz-text-size-adjust', '100%']
      - ['html', '-ms-text-size-adjust', '100%']
      - ['html', '-webkit-text-size-adjust', '100%']
      - ['*', 'box-sizing', 'inherit']
      - ['html', 'font-family', 'sans-serif']
    search:
      - '@-moz-viewport'
      - '@-ms-viewport'
      - '@-o-viewport'
      - '@-webkit-viewport'
      - '@viewport'
    search_not:
      - ['@media.+\(.*max-width', 'Media queries with `max-width` should not be used — use `min-width` instead']
      - ['@media.+\(.*px', 'Pixel units should not be used in media queries — use `em` instead']
      - ['font-size\s*:\s*.+px', 'Pixel units should not be used for `font-size` — use `rem` instead']

  - path: 'css/grid.css'
    valid: true
    bestPractices: true
    search:
      - 'https\:\/\/gridifier\.web\-dev\.tools\/\#xs\,4\,0\,0\,0\;s\,4\,25\,0\,0\;m\,4\,38\,1\,1\;l\,4\,60\,1\,1'

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]
